version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - cluster.name=knowledgebase-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - knowledgebase_network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.1
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - knowledgebase_network

  haystack:
    image: deepset/haystack:latest
    container_name: haystack
    environment:
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/knowledgebase_db
    ports:
      - "8000:8000"
    networks:
      - knowledgebase_network

  streamlit:
    image: streamlit/streamlit:latest
    container_name: streamlit
    ports:
      - "8501:8501"
    networks:
      - knowledgebase_network
    volumes:
      - ./streamlit:/app

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_DB: knowledgebase_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - knowledgebase_network

volumes:
  esdata:
    driver: local
  pgdata:
    driver: local

networks:
  knowledgebase_network:
    driver: bridge
