services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.14.1
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: knowledgebase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:80"
    depends_on:
      - elasticsearch
      - postgres
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend

  haystack:
    build:
      context: ./haystack
      container_name: haystack
    volumes:
      - ./backend:/app
    depends_on:
      - elasticsearch
      - postgres

  streamlit:
    image: streamlit/streamlit:latest
    container_name: streamlit
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app

volumes:
  esdata:
    driver: local
  pgdata:
    driver: local

